name: 🛠️ New Testcase
description: Add new testcase
title: " "
labels: [manual]
body:
- type: textarea
  attributes:
    label: Steps
    description: Test steps
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behaviour
    description: Expected behaviour
  validations:
    required: true
